/*
 * clients
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.clients.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Describes the role of a client/group in the system
 */
@ApiModel(description = "Describes the role of a client/group in the system")
@JsonPropertyOrder({
  ClientRole.JSON_PROPERTY_CLIENT_TYPE,
  ClientRole.JSON_PROPERTY_REQUIRE_I_D,
  ClientRole.JSON_PROPERTY_CAN_GUARANTEE,
  ClientRole.JSON_PROPERTY_USE_DEFAULT_ADDRESS,
  ClientRole.JSON_PROPERTY_NAME,
  ClientRole.JSON_PROPERTY_CAN_OPEN_ACCOUNTS,
  ClientRole.JSON_PROPERTY_DESCRIPTION,
  ClientRole.JSON_PROPERTY_ENCODED_KEY,
  ClientRole.JSON_PROPERTY_ID,
  ClientRole.JSON_PROPERTY_CREATION_DATE
})

public class ClientRole {
  /**
   * The type of the client for which this role was created
   */
  public enum ClientTypeEnum {
    CLIENT("CLIENT"),
    
    GROUP("GROUP");

    private String value;

    ClientTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ClientTypeEnum fromValue(String value) {
      for (ClientTypeEnum b : ClientTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CLIENT_TYPE = "clientType";
  private ClientTypeEnum clientType;

  public static final String JSON_PROPERTY_REQUIRE_I_D = "requireID";
  private Boolean requireID;

  public static final String JSON_PROPERTY_CAN_GUARANTEE = "canGuarantee";
  private Boolean canGuarantee;

  public static final String JSON_PROPERTY_USE_DEFAULT_ADDRESS = "useDefaultAddress";
  private Boolean useDefaultAddress;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_CAN_OPEN_ACCOUNTS = "canOpenAccounts";
  private Boolean canOpenAccounts;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_ENCODED_KEY = "encodedKey";
  private String encodedKey;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_CREATION_DATE = "creationDate";
  private OffsetDateTime creationDate;


  public ClientRole clientType(ClientTypeEnum clientType) {
    
    this.clientType = clientType;
    return this;
  }

   /**
   * The type of the client for which this role was created
   * @return clientType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of the client for which this role was created")
  @JsonProperty(JSON_PROPERTY_CLIENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ClientTypeEnum getClientType() {
    return clientType;
  }


  public void setClientType(ClientTypeEnum clientType) {
    this.clientType = clientType;
  }


  public ClientRole requireID(Boolean requireID) {
    
    this.requireID = requireID;
    return this;
  }

   /**
   * Indicates whether identification documents must be provided for the client to be created
   * @return requireID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether identification documents must be provided for the client to be created")
  @JsonProperty(JSON_PROPERTY_REQUIRE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRequireID() {
    return requireID;
  }


  public void setRequireID(Boolean requireID) {
    this.requireID = requireID;
  }


  public ClientRole canGuarantee(Boolean canGuarantee) {
    
    this.canGuarantee = canGuarantee;
    return this;
  }

   /**
   * Indicates whether the clients under this type can be used as guarantors
   * @return canGuarantee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether the clients under this type can be used as guarantors")
  @JsonProperty(JSON_PROPERTY_CAN_GUARANTEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanGuarantee() {
    return canGuarantee;
  }


  public void setCanGuarantee(Boolean canGuarantee) {
    this.canGuarantee = canGuarantee;
  }


  public ClientRole useDefaultAddress(Boolean useDefaultAddress) {
    
    this.useDefaultAddress = useDefaultAddress;
    return this;
  }

   /**
   * Indicates whether the Mambu default address section will be available
   * @return useDefaultAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether the Mambu default address section will be available")
  @JsonProperty(JSON_PROPERTY_USE_DEFAULT_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUseDefaultAddress() {
    return useDefaultAddress;
  }


  public void setUseDefaultAddress(Boolean useDefaultAddress) {
    this.useDefaultAddress = useDefaultAddress;
  }


  public ClientRole name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the client role
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the client role")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ClientRole canOpenAccounts(Boolean canOpenAccounts) {
    
    this.canOpenAccounts = canOpenAccounts;
    return this;
  }

   /**
   * Indicates whether new accounts for this client type can be created
   * @return canOpenAccounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether new accounts for this client type can be created")
  @JsonProperty(JSON_PROPERTY_CAN_OPEN_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanOpenAccounts() {
    return canOpenAccounts;
  }


  public void setCanOpenAccounts(Boolean canOpenAccounts) {
    this.canOpenAccounts = canOpenAccounts;
  }


  public ClientRole description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Text description for this client role
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Text description for this client role")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


   /**
   * The encoded key of the client, auto generated, unique
   * @return encodedKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The encoded key of the client, auto generated, unique")
  @JsonProperty(JSON_PROPERTY_ENCODED_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEncodedKey() {
    return encodedKey;
  }




  public ClientRole id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the client role, can be generated and customized, unique
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the client role, can be generated and customized, unique")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


   /**
   * The creation date of the client role
   * @return creationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2016-09-06T13:37:50+03:00", value = "The creation date of the client role")
  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreationDate() {
    return creationDate;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientRole clientRole = (ClientRole) o;
    return Objects.equals(this.clientType, clientRole.clientType) &&
        Objects.equals(this.requireID, clientRole.requireID) &&
        Objects.equals(this.canGuarantee, clientRole.canGuarantee) &&
        Objects.equals(this.useDefaultAddress, clientRole.useDefaultAddress) &&
        Objects.equals(this.name, clientRole.name) &&
        Objects.equals(this.canOpenAccounts, clientRole.canOpenAccounts) &&
        Objects.equals(this.description, clientRole.description) &&
        Objects.equals(this.encodedKey, clientRole.encodedKey) &&
        Objects.equals(this.id, clientRole.id) &&
        Objects.equals(this.creationDate, clientRole.creationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientType, requireID, canGuarantee, useDefaultAddress, name, canOpenAccounts, description, encodedKey, id, creationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientRole {\n");
    sb.append("    clientType: ").append(toIndentedString(clientType)).append("\n");
    sb.append("    requireID: ").append(toIndentedString(requireID)).append("\n");
    sb.append("    canGuarantee: ").append(toIndentedString(canGuarantee)).append("\n");
    sb.append("    useDefaultAddress: ").append(toIndentedString(useDefaultAddress)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    canOpenAccounts: ").append(toIndentedString(canOpenAccounts)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    encodedKey: ").append(toIndentedString(encodedKey)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

