/*
 * clients
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.clients.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Portal settings for an individual client
 */
@ApiModel(description = "Portal settings for an individual client")
@JsonPropertyOrder({
  PortalSettings.JSON_PROPERTY_ENCODED_KEY,
  PortalSettings.JSON_PROPERTY_PORTAL_STATE,
  PortalSettings.JSON_PROPERTY_LAST_LOGGED_IN_DATE
})

public class PortalSettings {
  public static final String JSON_PROPERTY_ENCODED_KEY = "encodedKey";
  private String encodedKey;

  /**
   * State of the client&#39;s portal preferences
   */
  public enum PortalStateEnum {
    ENABLED("ENABLED"),
    
    DISABLED("DISABLED");

    private String value;

    PortalStateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PortalStateEnum fromValue(String value) {
      for (PortalStateEnum b : PortalStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PORTAL_STATE = "portalState";
  private PortalStateEnum portalState;

  public static final String JSON_PROPERTY_LAST_LOGGED_IN_DATE = "lastLoggedInDate";
  private OffsetDateTime lastLoggedInDate;


   /**
   * The encoded key of the entity, generated, globally unique
   * @return encodedKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The encoded key of the entity, generated, globally unique")
  @JsonProperty(JSON_PROPERTY_ENCODED_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEncodedKey() {
    return encodedKey;
  }




  public PortalSettings portalState(PortalStateEnum portalState) {
    
    this.portalState = portalState;
    return this;
  }

   /**
   * State of the client&#39;s portal preferences
   * @return portalState
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "State of the client's portal preferences")
  @JsonProperty(JSON_PROPERTY_PORTAL_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PortalStateEnum getPortalState() {
    return portalState;
  }


  public void setPortalState(PortalStateEnum portalState) {
    this.portalState = portalState;
  }


  public PortalSettings lastLoggedInDate(OffsetDateTime lastLoggedInDate) {
    
    this.lastLoggedInDate = lastLoggedInDate;
    return this;
  }

   /**
   * The last date the client logged in to the portal
   * @return lastLoggedInDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2016-09-06T13:37:50+03:00", value = "The last date the client logged in to the portal")
  @JsonProperty(JSON_PROPERTY_LAST_LOGGED_IN_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastLoggedInDate() {
    return lastLoggedInDate;
  }


  public void setLastLoggedInDate(OffsetDateTime lastLoggedInDate) {
    this.lastLoggedInDate = lastLoggedInDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PortalSettings portalSettings = (PortalSettings) o;
    return Objects.equals(this.encodedKey, portalSettings.encodedKey) &&
        Objects.equals(this.portalState, portalSettings.portalState) &&
        Objects.equals(this.lastLoggedInDate, portalSettings.lastLoggedInDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(encodedKey, portalState, lastLoggedInDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PortalSettings {\n");
    sb.append("    encodedKey: ").append(toIndentedString(encodedKey)).append("\n");
    sb.append("    portalState: ").append(toIndentedString(portalState)).append("\n");
    sb.append("    lastLoggedInDate: ").append(toIndentedString(lastLoggedInDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

