/*
 * deposits
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.deposit.accounts.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Represents a request for applying the accrued interest 
 */
@ApiModel(description = "Represents a request for applying the accrued interest ")
@JsonPropertyOrder({
  ApplyInterestInput.JSON_PROPERTY_INTEREST_APPLICATION_DATE,
  ApplyInterestInput.JSON_PROPERTY_NOTES
})

public class ApplyInterestInput {
  public static final String JSON_PROPERTY_INTEREST_APPLICATION_DATE = "interestApplicationDate";
  private OffsetDateTime interestApplicationDate;

  public static final String JSON_PROPERTY_NOTES = "notes";
  private String notes;


  public ApplyInterestInput interestApplicationDate(OffsetDateTime interestApplicationDate) {
    
    this.interestApplicationDate = interestApplicationDate;
    return this;
  }

   /**
   * The date up to which interest is to be posted
   * @return interestApplicationDate
  **/
  @ApiModelProperty(example = "2016-09-06T13:37:50+03:00", required = true, value = "The date up to which interest is to be posted")
  @JsonProperty(JSON_PROPERTY_INTEREST_APPLICATION_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getInterestApplicationDate() {
    return interestApplicationDate;
  }


  public void setInterestApplicationDate(OffsetDateTime interestApplicationDate) {
    this.interestApplicationDate = interestApplicationDate;
  }


  public ApplyInterestInput notes(String notes) {
    
    this.notes = notes;
    return this;
  }

   /**
   * Additional information for this action
   * @return notes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional information for this action")
  @JsonProperty(JSON_PROPERTY_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNotes() {
    return notes;
  }


  public void setNotes(String notes) {
    this.notes = notes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplyInterestInput applyInterestInput = (ApplyInterestInput) o;
    return Objects.equals(this.interestApplicationDate, applyInterestInput.interestApplicationDate) &&
        Objects.equals(this.notes, applyInterestInput.notes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interestApplicationDate, notes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplyInterestInput {\n");
    sb.append("    interestApplicationDate: ").append(toIndentedString(interestApplicationDate)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

