/*
 * deposits
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.deposit.accounts.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The details of the card acceptor (merchant) in a transaction hold.
 */
@ApiModel(description = "The details of the card acceptor (merchant) in a transaction hold.")
@JsonPropertyOrder({
  CardAcceptor.JSON_PROPERTY_ZIP,
  CardAcceptor.JSON_PROPERTY_COUNTRY,
  CardAcceptor.JSON_PROPERTY_CITY,
  CardAcceptor.JSON_PROPERTY_STREET,
  CardAcceptor.JSON_PROPERTY_NAME,
  CardAcceptor.JSON_PROPERTY_STATE,
  CardAcceptor.JSON_PROPERTY_MCC
})

public class CardAcceptor {
  public static final String JSON_PROPERTY_ZIP = "zip";
  private String zip;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private String country;

  public static final String JSON_PROPERTY_CITY = "city";
  private String city;

  public static final String JSON_PROPERTY_STREET = "street";
  private String street;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_STATE = "state";
  private String state;

  public static final String JSON_PROPERTY_MCC = "mcc";
  private Integer mcc;


  public CardAcceptor zip(String zip) {
    
    this.zip = zip;
    return this;
  }

   /**
   * The ZIP code of the location in which the card acceptor has the business.
   * @return zip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ZIP code of the location in which the card acceptor has the business.")
  @JsonProperty(JSON_PROPERTY_ZIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getZip() {
    return zip;
  }


  public void setZip(String zip) {
    this.zip = zip;
  }


  public CardAcceptor country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * The country in which the card acceptor has the business.
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The country in which the card acceptor has the business.")
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public CardAcceptor city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * The city in which the card acceptor has the business.
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The city in which the card acceptor has the business.")
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public CardAcceptor street(String street) {
    
    this.street = street;
    return this;
  }

   /**
   * The street in which the card acceptor has the business.
   * @return street
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The street in which the card acceptor has the business.")
  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStreet() {
    return street;
  }


  public void setStreet(String street) {
    this.street = street;
  }


  public CardAcceptor name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the card acceptor.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the card acceptor.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CardAcceptor state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * The state in which the card acceptor has the business.
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The state in which the card acceptor has the business.")
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  public CardAcceptor mcc(Integer mcc) {
    
    this.mcc = mcc;
    return this;
  }

   /**
   * The Merchant Category Code of the card acceptor.
   * @return mcc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The Merchant Category Code of the card acceptor.")
  @JsonProperty(JSON_PROPERTY_MCC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMcc() {
    return mcc;
  }


  public void setMcc(Integer mcc) {
    this.mcc = mcc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardAcceptor cardAcceptor = (CardAcceptor) o;
    return Objects.equals(this.zip, cardAcceptor.zip) &&
        Objects.equals(this.country, cardAcceptor.country) &&
        Objects.equals(this.city, cardAcceptor.city) &&
        Objects.equals(this.street, cardAcceptor.street) &&
        Objects.equals(this.name, cardAcceptor.name) &&
        Objects.equals(this.state, cardAcceptor.state) &&
        Objects.equals(this.mcc, cardAcceptor.mcc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(zip, country, city, street, name, state, mcc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardAcceptor {\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    mcc: ").append(toIndentedString(mcc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

