/*
 * depositproducts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.deposit.products.model;

import java.util.Objects;
import java.util.Arrays;
import com.backbase.mambu.deposit.products.model.DecimalInterval;
import com.backbase.mambu.deposit.products.model.DepositProductInterestRateTier;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The interest settings, defines constraints regarding interest that will be used on the deposit created based on this product.
 */
@ApiModel(description = "The interest settings, defines constraints regarding interest that will be used on the deposit created based on this product.")
@JsonPropertyOrder({
  DepositProductInterestRateSettings.JSON_PROPERTY_INTEREST_RATE,
  DepositProductInterestRateSettings.JSON_PROPERTY_INTEREST_RATE_SOURCE,
  DepositProductInterestRateSettings.JSON_PROPERTY_INDEX_SOURCE_KEY,
  DepositProductInterestRateSettings.JSON_PROPERTY_INTEREST_RATE_TIERS,
  DepositProductInterestRateSettings.JSON_PROPERTY_INTEREST_CHARGE_FREQUENCY,
  DepositProductInterestRateSettings.JSON_PROPERTY_ACCRUE_INTEREST_AFTER_MATURITY,
  DepositProductInterestRateSettings.JSON_PROPERTY_ENCODED_KEY,
  DepositProductInterestRateSettings.JSON_PROPERTY_INTEREST_RATE_TERMS,
  DepositProductInterestRateSettings.JSON_PROPERTY_INTEREST_CHARGE_FREQUENCY_COUNT
})

public class DepositProductInterestRateSettings {
  public static final String JSON_PROPERTY_INTEREST_RATE = "interestRate";
  private DecimalInterval interestRate;

  /**
   * Interest calculation method: fixed or (interest spread + active organization index interest rate)
   */
  public enum InterestRateSourceEnum {
    FIXED_INTEREST_RATE("FIXED_INTEREST_RATE"),
    
    INDEX_INTEREST_RATE("INDEX_INTEREST_RATE");

    private String value;

    InterestRateSourceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InterestRateSourceEnum fromValue(String value) {
      for (InterestRateSourceEnum b : InterestRateSourceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INTEREST_RATE_SOURCE = "interestRateSource";
  private InterestRateSourceEnum interestRateSource;

  public static final String JSON_PROPERTY_INDEX_SOURCE_KEY = "indexSourceKey";
  private String indexSourceKey;

  public static final String JSON_PROPERTY_INTEREST_RATE_TIERS = "interestRateTiers";
  private List<DepositProductInterestRateTier> interestRateTiers = null;

  /**
   * The interval used for determining how often is interest charged
   */
  public enum InterestChargeFrequencyEnum {
    ANNUALIZED("ANNUALIZED"),
    
    EVERY_MONTH("EVERY_MONTH"),
    
    EVERY_FOUR_WEEKS("EVERY_FOUR_WEEKS"),
    
    EVERY_WEEK("EVERY_WEEK"),
    
    EVERY_DAY("EVERY_DAY"),
    
    EVERY_X_DAYS("EVERY_X_DAYS");

    private String value;

    InterestChargeFrequencyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InterestChargeFrequencyEnum fromValue(String value) {
      for (InterestChargeFrequencyEnum b : InterestChargeFrequencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INTEREST_CHARGE_FREQUENCY = "interestChargeFrequency";
  private InterestChargeFrequencyEnum interestChargeFrequency;

  public static final String JSON_PROPERTY_ACCRUE_INTEREST_AFTER_MATURITY = "accrueInterestAfterMaturity";
  private Boolean accrueInterestAfterMaturity;

  public static final String JSON_PROPERTY_ENCODED_KEY = "encodedKey";
  private String encodedKey;

  /**
   * The option for how is the interest rate determined when being accrued for an account
   */
  public enum InterestRateTermsEnum {
    FIXED("FIXED"),
    
    TIERED("TIERED"),
    
    TIERED_PERIOD("TIERED_PERIOD");

    private String value;

    InterestRateTermsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InterestRateTermsEnum fromValue(String value) {
      for (InterestRateTermsEnum b : InterestRateTermsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INTEREST_RATE_TERMS = "interestRateTerms";
  private InterestRateTermsEnum interestRateTerms;

  public static final String JSON_PROPERTY_INTEREST_CHARGE_FREQUENCY_COUNT = "interestChargeFrequencyCount";
  private Integer interestChargeFrequencyCount;


  public DepositProductInterestRateSettings interestRate(DecimalInterval interestRate) {
    
    this.interestRate = interestRate;
    return this;
  }

   /**
   * Get interestRate
   * @return interestRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DecimalInterval getInterestRate() {
    return interestRate;
  }


  public void setInterestRate(DecimalInterval interestRate) {
    this.interestRate = interestRate;
  }


  public DepositProductInterestRateSettings interestRateSource(InterestRateSourceEnum interestRateSource) {
    
    this.interestRateSource = interestRateSource;
    return this;
  }

   /**
   * Interest calculation method: fixed or (interest spread + active organization index interest rate)
   * @return interestRateSource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Interest calculation method: fixed or (interest spread + active organization index interest rate)")
  @JsonProperty(JSON_PROPERTY_INTEREST_RATE_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InterestRateSourceEnum getInterestRateSource() {
    return interestRateSource;
  }


  public void setInterestRateSource(InterestRateSourceEnum interestRateSource) {
    this.interestRateSource = interestRateSource;
  }


  public DepositProductInterestRateSettings indexSourceKey(String indexSourceKey) {
    
    this.indexSourceKey = indexSourceKey;
    return this;
  }

   /**
   * Index rate source key.
   * @return indexSourceKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Index rate source key.")
  @JsonProperty(JSON_PROPERTY_INDEX_SOURCE_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIndexSourceKey() {
    return indexSourceKey;
  }


  public void setIndexSourceKey(String indexSourceKey) {
    this.indexSourceKey = indexSourceKey;
  }


  public DepositProductInterestRateSettings interestRateTiers(List<DepositProductInterestRateTier> interestRateTiers) {
    
    this.interestRateTiers = interestRateTiers;
    return this;
  }

  public DepositProductInterestRateSettings addInterestRateTiersItem(DepositProductInterestRateTier interestRateTiersItem) {
    if (this.interestRateTiers == null) {
      this.interestRateTiers = new ArrayList<>();
    }
    this.interestRateTiers.add(interestRateTiersItem);
    return this;
  }

   /**
   * The list of interest rate tiers available for the current settings instance
   * @return interestRateTiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of interest rate tiers available for the current settings instance")
  @JsonProperty(JSON_PROPERTY_INTEREST_RATE_TIERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DepositProductInterestRateTier> getInterestRateTiers() {
    return interestRateTiers;
  }


  public void setInterestRateTiers(List<DepositProductInterestRateTier> interestRateTiers) {
    this.interestRateTiers = interestRateTiers;
  }


  public DepositProductInterestRateSettings interestChargeFrequency(InterestChargeFrequencyEnum interestChargeFrequency) {
    
    this.interestChargeFrequency = interestChargeFrequency;
    return this;
  }

   /**
   * The interval used for determining how often is interest charged
   * @return interestChargeFrequency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The interval used for determining how often is interest charged")
  @JsonProperty(JSON_PROPERTY_INTEREST_CHARGE_FREQUENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InterestChargeFrequencyEnum getInterestChargeFrequency() {
    return interestChargeFrequency;
  }


  public void setInterestChargeFrequency(InterestChargeFrequencyEnum interestChargeFrequency) {
    this.interestChargeFrequency = interestChargeFrequency;
  }


  public DepositProductInterestRateSettings accrueInterestAfterMaturity(Boolean accrueInterestAfterMaturity) {
    
    this.accrueInterestAfterMaturity = accrueInterestAfterMaturity;
    return this;
  }

   /**
   * If the product supports this option, specify if the interest should be accrued after the account maturity date
   * @return accrueInterestAfterMaturity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If the product supports this option, specify if the interest should be accrued after the account maturity date")
  @JsonProperty(JSON_PROPERTY_ACCRUE_INTEREST_AFTER_MATURITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAccrueInterestAfterMaturity() {
    return accrueInterestAfterMaturity;
  }


  public void setAccrueInterestAfterMaturity(Boolean accrueInterestAfterMaturity) {
    this.accrueInterestAfterMaturity = accrueInterestAfterMaturity;
  }


   /**
   * The encoded key of the interest rate tier, auto generated, unique
   * @return encodedKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The encoded key of the interest rate tier, auto generated, unique")
  @JsonProperty(JSON_PROPERTY_ENCODED_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEncodedKey() {
    return encodedKey;
  }




  public DepositProductInterestRateSettings interestRateTerms(InterestRateTermsEnum interestRateTerms) {
    
    this.interestRateTerms = interestRateTerms;
    return this;
  }

   /**
   * The option for how is the interest rate determined when being accrued for an account
   * @return interestRateTerms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The option for how is the interest rate determined when being accrued for an account")
  @JsonProperty(JSON_PROPERTY_INTEREST_RATE_TERMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InterestRateTermsEnum getInterestRateTerms() {
    return interestRateTerms;
  }


  public void setInterestRateTerms(InterestRateTermsEnum interestRateTerms) {
    this.interestRateTerms = interestRateTerms;
  }


  public DepositProductInterestRateSettings interestChargeFrequencyCount(Integer interestChargeFrequencyCount) {
    
    this.interestChargeFrequencyCount = interestChargeFrequencyCount;
    return this;
  }

   /**
   * the count of units to apply over the interval
   * @return interestChargeFrequencyCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the count of units to apply over the interval")
  @JsonProperty(JSON_PROPERTY_INTEREST_CHARGE_FREQUENCY_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInterestChargeFrequencyCount() {
    return interestChargeFrequencyCount;
  }


  public void setInterestChargeFrequencyCount(Integer interestChargeFrequencyCount) {
    this.interestChargeFrequencyCount = interestChargeFrequencyCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositProductInterestRateSettings depositProductInterestRateSettings = (DepositProductInterestRateSettings) o;
    return Objects.equals(this.interestRate, depositProductInterestRateSettings.interestRate) &&
        Objects.equals(this.interestRateSource, depositProductInterestRateSettings.interestRateSource) &&
        Objects.equals(this.indexSourceKey, depositProductInterestRateSettings.indexSourceKey) &&
        Objects.equals(this.interestRateTiers, depositProductInterestRateSettings.interestRateTiers) &&
        Objects.equals(this.interestChargeFrequency, depositProductInterestRateSettings.interestChargeFrequency) &&
        Objects.equals(this.accrueInterestAfterMaturity, depositProductInterestRateSettings.accrueInterestAfterMaturity) &&
        Objects.equals(this.encodedKey, depositProductInterestRateSettings.encodedKey) &&
        Objects.equals(this.interestRateTerms, depositProductInterestRateSettings.interestRateTerms) &&
        Objects.equals(this.interestChargeFrequencyCount, depositProductInterestRateSettings.interestChargeFrequencyCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interestRate, interestRateSource, indexSourceKey, interestRateTiers, interestChargeFrequency, accrueInterestAfterMaturity, encodedKey, interestRateTerms, interestChargeFrequencyCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositProductInterestRateSettings {\n");
    sb.append("    interestRate: ").append(toIndentedString(interestRate)).append("\n");
    sb.append("    interestRateSource: ").append(toIndentedString(interestRateSource)).append("\n");
    sb.append("    indexSourceKey: ").append(toIndentedString(indexSourceKey)).append("\n");
    sb.append("    interestRateTiers: ").append(toIndentedString(interestRateTiers)).append("\n");
    sb.append("    interestChargeFrequency: ").append(toIndentedString(interestChargeFrequency)).append("\n");
    sb.append("    accrueInterestAfterMaturity: ").append(toIndentedString(accrueInterestAfterMaturity)).append("\n");
    sb.append("    encodedKey: ").append(toIndentedString(encodedKey)).append("\n");
    sb.append("    interestRateTerms: ").append(toIndentedString(interestRateTerms)).append("\n");
    sb.append("    interestChargeFrequencyCount: ").append(toIndentedString(interestChargeFrequencyCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

