/*
 * depositproducts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.deposit.products.model;

import java.util.Objects;
import java.util.Arrays;
import com.backbase.mambu.deposit.products.model.AmountDecimalInterval;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Constraints and automated actions and that will be applied on the accounts.
 */
@ApiModel(description = "Constraints and automated actions and that will be applied on the accounts.")
@JsonPropertyOrder({
  DepositProductInternalControls.JSON_PROPERTY_DORMANCY_PERIOD_DAYS,
  DepositProductInternalControls.JSON_PROPERTY_RECOMMENDED_DEPOSIT_AMOUNT,
  DepositProductInternalControls.JSON_PROPERTY_OPENING_BALANCE,
  DepositProductInternalControls.JSON_PROPERTY_MAX_WITHDRAWAL_AMOUNT
})

public class DepositProductInternalControls {
  public static final String JSON_PROPERTY_DORMANCY_PERIOD_DAYS = "dormancyPeriodDays";
  private Integer dormancyPeriodDays;

  public static final String JSON_PROPERTY_RECOMMENDED_DEPOSIT_AMOUNT = "recommendedDepositAmount";
  private BigDecimal recommendedDepositAmount;

  public static final String JSON_PROPERTY_OPENING_BALANCE = "openingBalance";
  private AmountDecimalInterval openingBalance;

  public static final String JSON_PROPERTY_MAX_WITHDRAWAL_AMOUNT = "maxWithdrawalAmount";
  private BigDecimal maxWithdrawalAmount;


  public DepositProductInternalControls dormancyPeriodDays(Integer dormancyPeriodDays) {
    
    this.dormancyPeriodDays = dormancyPeriodDays;
    return this;
  }

   /**
   * Specifies the number of days for an account to be fully paid in order to auto close it.
   * @return dormancyPeriodDays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies the number of days for an account to be fully paid in order to auto close it.")
  @JsonProperty(JSON_PROPERTY_DORMANCY_PERIOD_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDormancyPeriodDays() {
    return dormancyPeriodDays;
  }


  public void setDormancyPeriodDays(Integer dormancyPeriodDays) {
    this.dormancyPeriodDays = dormancyPeriodDays;
  }


  public DepositProductInternalControls recommendedDepositAmount(BigDecimal recommendedDepositAmount) {
    
    this.recommendedDepositAmount = recommendedDepositAmount;
    return this;
  }

   /**
   * Recommended amount for a deposit
   * @return recommendedDepositAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Recommended amount for a deposit")
  @JsonProperty(JSON_PROPERTY_RECOMMENDED_DEPOSIT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getRecommendedDepositAmount() {
    return recommendedDepositAmount;
  }


  public void setRecommendedDepositAmount(BigDecimal recommendedDepositAmount) {
    this.recommendedDepositAmount = recommendedDepositAmount;
  }


  public DepositProductInternalControls openingBalance(AmountDecimalInterval openingBalance) {
    
    this.openingBalance = openingBalance;
    return this;
  }

   /**
   * Get openingBalance
   * @return openingBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OPENING_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AmountDecimalInterval getOpeningBalance() {
    return openingBalance;
  }


  public void setOpeningBalance(AmountDecimalInterval openingBalance) {
    this.openingBalance = openingBalance;
  }


  public DepositProductInternalControls maxWithdrawalAmount(BigDecimal maxWithdrawalAmount) {
    
    this.maxWithdrawalAmount = maxWithdrawalAmount;
    return this;
  }

   /**
   * Max amount per withdrawal
   * @return maxWithdrawalAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Max amount per withdrawal")
  @JsonProperty(JSON_PROPERTY_MAX_WITHDRAWAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getMaxWithdrawalAmount() {
    return maxWithdrawalAmount;
  }


  public void setMaxWithdrawalAmount(BigDecimal maxWithdrawalAmount) {
    this.maxWithdrawalAmount = maxWithdrawalAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositProductInternalControls depositProductInternalControls = (DepositProductInternalControls) o;
    return Objects.equals(this.dormancyPeriodDays, depositProductInternalControls.dormancyPeriodDays) &&
        Objects.equals(this.recommendedDepositAmount, depositProductInternalControls.recommendedDepositAmount) &&
        Objects.equals(this.openingBalance, depositProductInternalControls.openingBalance) &&
        Objects.equals(this.maxWithdrawalAmount, depositProductInternalControls.maxWithdrawalAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dormancyPeriodDays, recommendedDepositAmount, openingBalance, maxWithdrawalAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositProductInternalControls {\n");
    sb.append("    dormancyPeriodDays: ").append(toIndentedString(dormancyPeriodDays)).append("\n");
    sb.append("    recommendedDepositAmount: ").append(toIndentedString(recommendedDepositAmount)).append("\n");
    sb.append("    openingBalance: ").append(toIndentedString(openingBalance)).append("\n");
    sb.append("    maxWithdrawalAmount: ").append(toIndentedString(maxWithdrawalAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

