/*
 * loanproducts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.loan.products.model;

import java.util.Objects;
import java.util.Arrays;
import com.backbase.mambu.loan.products.model.IntegerIntervalConstraints;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The funding settings, holds the settings regarding the funding for the loan product.
 */
@ApiModel(description = "The funding settings, holds the settings regarding the funding for the loan product.")
@JsonPropertyOrder({
  GracePeriodSettings.JSON_PROPERTY_GRACE_PERIOD,
  GracePeriodSettings.JSON_PROPERTY_GRACE_PERIOD_TYPE
})

public class GracePeriodSettings {
  public static final String JSON_PROPERTY_GRACE_PERIOD = "gracePeriod";
  private IntegerIntervalConstraints gracePeriod;

  /**
   * The grace period type. Representing the type of grace period which is possible for a loan account.
   */
  public enum GracePeriodTypeEnum {
    NONE("NONE"),
    
    PAY_INTEREST_ONLY("PAY_INTEREST_ONLY"),
    
    INTEREST_FORGIVENESS("INTEREST_FORGIVENESS");

    private String value;

    GracePeriodTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GracePeriodTypeEnum fromValue(String value) {
      for (GracePeriodTypeEnum b : GracePeriodTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_GRACE_PERIOD_TYPE = "gracePeriodType";
  private GracePeriodTypeEnum gracePeriodType;


  public GracePeriodSettings gracePeriod(IntegerIntervalConstraints gracePeriod) {
    
    this.gracePeriod = gracePeriod;
    return this;
  }

   /**
   * Get gracePeriod
   * @return gracePeriod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GRACE_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IntegerIntervalConstraints getGracePeriod() {
    return gracePeriod;
  }


  public void setGracePeriod(IntegerIntervalConstraints gracePeriod) {
    this.gracePeriod = gracePeriod;
  }


  public GracePeriodSettings gracePeriodType(GracePeriodTypeEnum gracePeriodType) {
    
    this.gracePeriodType = gracePeriodType;
    return this;
  }

   /**
   * The grace period type. Representing the type of grace period which is possible for a loan account.
   * @return gracePeriodType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The grace period type. Representing the type of grace period which is possible for a loan account.")
  @JsonProperty(JSON_PROPERTY_GRACE_PERIOD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GracePeriodTypeEnum getGracePeriodType() {
    return gracePeriodType;
  }


  public void setGracePeriodType(GracePeriodTypeEnum gracePeriodType) {
    this.gracePeriodType = gracePeriodType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GracePeriodSettings gracePeriodSettings = (GracePeriodSettings) o;
    return Objects.equals(this.gracePeriod, gracePeriodSettings.gracePeriod) &&
        Objects.equals(this.gracePeriodType, gracePeriodSettings.gracePeriodType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gracePeriod, gracePeriodType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GracePeriodSettings {\n");
    sb.append("    gracePeriod: ").append(toIndentedString(gracePeriod)).append("\n");
    sb.append("    gracePeriodType: ").append(toIndentedString(gracePeriodType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

