/*
 * loanproducts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.loan.products.model;

import java.util.Objects;
import java.util.Arrays;
import com.backbase.mambu.loan.products.model.LockSettings;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Constraints and automated actions and that will be applied on the accounts.
 */
@ApiModel(description = "Constraints and automated actions and that will be applied on the accounts.")
@JsonPropertyOrder({
  InternalControls.JSON_PROPERTY_DORMANCY_PERIOD_DAYS,
  InternalControls.JSON_PROPERTY_LOCK_SETTINGS
})

public class InternalControls {
  public static final String JSON_PROPERTY_DORMANCY_PERIOD_DAYS = "dormancyPeriodDays";
  private Integer dormancyPeriodDays;

  public static final String JSON_PROPERTY_LOCK_SETTINGS = "lockSettings";
  private LockSettings lockSettings;


  public InternalControls dormancyPeriodDays(Integer dormancyPeriodDays) {
    
    this.dormancyPeriodDays = dormancyPeriodDays;
    return this;
  }

   /**
   * Specifies the number of days for an account to be fully paid in order to auto close it.
   * @return dormancyPeriodDays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies the number of days for an account to be fully paid in order to auto close it.")
  @JsonProperty(JSON_PROPERTY_DORMANCY_PERIOD_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDormancyPeriodDays() {
    return dormancyPeriodDays;
  }


  public void setDormancyPeriodDays(Integer dormancyPeriodDays) {
    this.dormancyPeriodDays = dormancyPeriodDays;
  }


  public InternalControls lockSettings(LockSettings lockSettings) {
    
    this.lockSettings = lockSettings;
    return this;
  }

   /**
   * Get lockSettings
   * @return lockSettings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCK_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LockSettings getLockSettings() {
    return lockSettings;
  }


  public void setLockSettings(LockSettings lockSettings) {
    this.lockSettings = lockSettings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternalControls internalControls = (InternalControls) o;
    return Objects.equals(this.dormancyPeriodDays, internalControls.dormancyPeriodDays) &&
        Objects.equals(this.lockSettings, internalControls.lockSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dormancyPeriodDays, lockSettings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternalControls {\n");
    sb.append("    dormancyPeriodDays: ").append(toIndentedString(dormancyPeriodDays)).append("\n");
    sb.append("    lockSettings: ").append(toIndentedString(lockSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

