/*
 * loanproducts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.loan.products.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Used or TIERED interest rates, holds the values to define how the interest is computed
 */
@ApiModel(description = "Used or TIERED interest rates, holds the values to define how the interest is computed")
@JsonPropertyOrder({
  InterestRateTier.JSON_PROPERTY_ENDING_BALANCE,
  InterestRateTier.JSON_PROPERTY_INTEREST_RATE,
  InterestRateTier.JSON_PROPERTY_ENCODED_KEY
})

public class InterestRateTier {
  public static final String JSON_PROPERTY_ENDING_BALANCE = "endingBalance";
  private BigDecimal endingBalance;

  public static final String JSON_PROPERTY_INTEREST_RATE = "interestRate";
  private BigDecimal interestRate;

  public static final String JSON_PROPERTY_ENCODED_KEY = "encodedKey";
  private String encodedKey;


  public InterestRateTier endingBalance(BigDecimal endingBalance) {
    
    this.endingBalance = endingBalance;
    return this;
  }

   /**
   * The top-limit value for the account balance in order to determine if this tier is used or not
   * @return endingBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The top-limit value for the account balance in order to determine if this tier is used or not")
  @JsonProperty(JSON_PROPERTY_ENDING_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getEndingBalance() {
    return endingBalance;
  }


  public void setEndingBalance(BigDecimal endingBalance) {
    this.endingBalance = endingBalance;
  }


  public InterestRateTier interestRate(BigDecimal interestRate) {
    
    this.interestRate = interestRate;
    return this;
  }

   /**
   * The rate used for computing the interest for an account which has the balance less than the ending balance
   * @return interestRate
  **/
  @ApiModelProperty(required = true, value = "The rate used for computing the interest for an account which has the balance less than the ending balance")
  @JsonProperty(JSON_PROPERTY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getInterestRate() {
    return interestRate;
  }


  public void setInterestRate(BigDecimal interestRate) {
    this.interestRate = interestRate;
  }


   /**
   * The encoded key of the interest rate tier, auto generated, unique
   * @return encodedKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The encoded key of the interest rate tier, auto generated, unique")
  @JsonProperty(JSON_PROPERTY_ENCODED_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEncodedKey() {
    return encodedKey;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InterestRateTier interestRateTier = (InterestRateTier) o;
    return Objects.equals(this.endingBalance, interestRateTier.endingBalance) &&
        Objects.equals(this.interestRate, interestRateTier.interestRate) &&
        Objects.equals(this.encodedKey, interestRateTier.encodedKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endingBalance, interestRate, encodedKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InterestRateTier {\n");
    sb.append("    endingBalance: ").append(toIndentedString(endingBalance)).append("\n");
    sb.append("    interestRate: ").append(toIndentedString(interestRate)).append("\n");
    sb.append("    encodedKey: ").append(toIndentedString(encodedKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

