/*
 * loanproducts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.loan.products.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The offset settings, holds information about offset.
 */
@ApiModel(description = "The offset settings, holds information about offset.")
@JsonPropertyOrder({
  OffsetSettings.JSON_PROPERTY_OFFSET_PERCENTAGE
})

public class OffsetSettings {
  public static final String JSON_PROPERTY_OFFSET_PERCENTAGE = "offsetPercentage";
  private BigDecimal offsetPercentage;


  public OffsetSettings offsetPercentage(BigDecimal offsetPercentage) {
    
    this.offsetPercentage = offsetPercentage;
    return this;
  }

   /**
   * The offset percentage
   * @return offsetPercentage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The offset percentage")
  @JsonProperty(JSON_PROPERTY_OFFSET_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getOffsetPercentage() {
    return offsetPercentage;
  }


  public void setOffsetPercentage(BigDecimal offsetPercentage) {
    this.offsetPercentage = offsetPercentage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OffsetSettings offsetSettings = (OffsetSettings) o;
    return Objects.equals(this.offsetPercentage, offsetSettings.offsetPercentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offsetPercentage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OffsetSettings {\n");
    sb.append("    offsetPercentage: ").append(toIndentedString(offsetPercentage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

