/*
 * loanproducts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.loan.products.model;

import java.util.Objects;
import java.util.Arrays;
import com.backbase.mambu.loan.products.model.DecimalConstraints;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Defines the penalty settings for the product that will be used by the loan accounts based on this product
 */
@ApiModel(description = "Defines the penalty settings for the product that will be used by the loan accounts based on this product")
@JsonPropertyOrder({
  ProductPenaltySettings.JSON_PROPERTY_LOAN_PENALTY_GRACE_PERIOD,
  ProductPenaltySettings.JSON_PROPERTY_LOAN_PENALTY_CALCULATION_METHOD,
  ProductPenaltySettings.JSON_PROPERTY_PENALTY_RATE
})

public class ProductPenaltySettings {
  public static final String JSON_PROPERTY_LOAN_PENALTY_GRACE_PERIOD = "loanPenaltyGracePeriod";
  private Integer loanPenaltyGracePeriod;

  /**
   * The penalty calculation method
   */
  public enum LoanPenaltyCalculationMethodEnum {
    NONE("NONE"),
    
    OVERDUE_BALANCE("OVERDUE_BALANCE"),
    
    OVERDUE_BALANCE_AND_INTEREST("OVERDUE_BALANCE_AND_INTEREST"),
    
    OUTSTANDING_PRINCIPAL("OUTSTANDING_PRINCIPAL");

    private String value;

    LoanPenaltyCalculationMethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LoanPenaltyCalculationMethodEnum fromValue(String value) {
      for (LoanPenaltyCalculationMethodEnum b : LoanPenaltyCalculationMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LOAN_PENALTY_CALCULATION_METHOD = "loanPenaltyCalculationMethod";
  private LoanPenaltyCalculationMethodEnum loanPenaltyCalculationMethod;

  public static final String JSON_PROPERTY_PENALTY_RATE = "penaltyRate";
  private DecimalConstraints penaltyRate;


  public ProductPenaltySettings loanPenaltyGracePeriod(Integer loanPenaltyGracePeriod) {
    
    this.loanPenaltyGracePeriod = loanPenaltyGracePeriod;
    return this;
  }

   /**
   * Number of days to wait before applying the loan penalty amounts
   * @return loanPenaltyGracePeriod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of days to wait before applying the loan penalty amounts")
  @JsonProperty(JSON_PROPERTY_LOAN_PENALTY_GRACE_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLoanPenaltyGracePeriod() {
    return loanPenaltyGracePeriod;
  }


  public void setLoanPenaltyGracePeriod(Integer loanPenaltyGracePeriod) {
    this.loanPenaltyGracePeriod = loanPenaltyGracePeriod;
  }


  public ProductPenaltySettings loanPenaltyCalculationMethod(LoanPenaltyCalculationMethodEnum loanPenaltyCalculationMethod) {
    
    this.loanPenaltyCalculationMethod = loanPenaltyCalculationMethod;
    return this;
  }

   /**
   * The penalty calculation method
   * @return loanPenaltyCalculationMethod
  **/
  @ApiModelProperty(required = true, value = "The penalty calculation method")
  @JsonProperty(JSON_PROPERTY_LOAN_PENALTY_CALCULATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LoanPenaltyCalculationMethodEnum getLoanPenaltyCalculationMethod() {
    return loanPenaltyCalculationMethod;
  }


  public void setLoanPenaltyCalculationMethod(LoanPenaltyCalculationMethodEnum loanPenaltyCalculationMethod) {
    this.loanPenaltyCalculationMethod = loanPenaltyCalculationMethod;
  }


  public ProductPenaltySettings penaltyRate(DecimalConstraints penaltyRate) {
    
    this.penaltyRate = penaltyRate;
    return this;
  }

   /**
   * Get penaltyRate
   * @return penaltyRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PENALTY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DecimalConstraints getPenaltyRate() {
    return penaltyRate;
  }


  public void setPenaltyRate(DecimalConstraints penaltyRate) {
    this.penaltyRate = penaltyRate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductPenaltySettings productPenaltySettings = (ProductPenaltySettings) o;
    return Objects.equals(this.loanPenaltyGracePeriod, productPenaltySettings.loanPenaltyGracePeriod) &&
        Objects.equals(this.loanPenaltyCalculationMethod, productPenaltySettings.loanPenaltyCalculationMethod) &&
        Objects.equals(this.penaltyRate, productPenaltySettings.penaltyRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loanPenaltyGracePeriod, loanPenaltyCalculationMethod, penaltyRate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductPenaltySettings {\n");
    sb.append("    loanPenaltyGracePeriod: ").append(toIndentedString(loanPenaltyGracePeriod)).append("\n");
    sb.append("    loanPenaltyCalculationMethod: ").append(toIndentedString(loanPenaltyCalculationMethod)).append("\n");
    sb.append("    penaltyRate: ").append(toIndentedString(penaltyRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

