/*
 * loanproducts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.loan.products.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The settings and constraints for securities.
 */
@ApiModel(description = "The settings and constraints for securities.")
@JsonPropertyOrder({
  SecuritySettings.JSON_PROPERTY_IS_COLLATERAL_ENABLED,
  SecuritySettings.JSON_PROPERTY_IS_GUARANTORS_ENABLED,
  SecuritySettings.JSON_PROPERTY_REQUIRED_GUARANTIES
})

public class SecuritySettings {
  public static final String JSON_PROPERTY_IS_COLLATERAL_ENABLED = "isCollateralEnabled";
  private Boolean isCollateralEnabled;

  public static final String JSON_PROPERTY_IS_GUARANTORS_ENABLED = "isGuarantorsEnabled";
  private Boolean isGuarantorsEnabled;

  public static final String JSON_PROPERTY_REQUIRED_GUARANTIES = "requiredGuaranties";
  private BigDecimal requiredGuaranties;


  public SecuritySettings isCollateralEnabled(Boolean isCollateralEnabled) {
    
    this.isCollateralEnabled = isCollateralEnabled;
    return this;
  }

   /**
   * Shows whether collateral (assets or other goods) are accepted in order to reach required securities percentage from loan amount, as defined in this product.
   * @return isCollateralEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Shows whether collateral (assets or other goods) are accepted in order to reach required securities percentage from loan amount, as defined in this product.")
  @JsonProperty(JSON_PROPERTY_IS_COLLATERAL_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsCollateralEnabled() {
    return isCollateralEnabled;
  }


  public void setIsCollateralEnabled(Boolean isCollateralEnabled) {
    this.isCollateralEnabled = isCollateralEnabled;
  }


  public SecuritySettings isGuarantorsEnabled(Boolean isGuarantorsEnabled) {
    
    this.isGuarantorsEnabled = isGuarantorsEnabled;
    return this;
  }

   /**
   * Shows whether guarantors (other clients) are accepted in order to reach the required securities percentage from loan amount, as defined in this product.
   * @return isGuarantorsEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Shows whether guarantors (other clients) are accepted in order to reach the required securities percentage from loan amount, as defined in this product.")
  @JsonProperty(JSON_PROPERTY_IS_GUARANTORS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsGuarantorsEnabled() {
    return isGuarantorsEnabled;
  }


  public void setIsGuarantorsEnabled(Boolean isGuarantorsEnabled) {
    this.isGuarantorsEnabled = isGuarantorsEnabled;
  }


  public SecuritySettings requiredGuaranties(BigDecimal requiredGuaranties) {
    
    this.requiredGuaranties = requiredGuaranties;
    return this;
  }

   /**
   * The securities percentage from loan amount that is needed in order for this account to be approved. Null if the securities are not required.
   * @return requiredGuaranties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The securities percentage from loan amount that is needed in order for this account to be approved. Null if the securities are not required.")
  @JsonProperty(JSON_PROPERTY_REQUIRED_GUARANTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getRequiredGuaranties() {
    return requiredGuaranties;
  }


  public void setRequiredGuaranties(BigDecimal requiredGuaranties) {
    this.requiredGuaranties = requiredGuaranties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecuritySettings securitySettings = (SecuritySettings) o;
    return Objects.equals(this.isCollateralEnabled, securitySettings.isCollateralEnabled) &&
        Objects.equals(this.isGuarantorsEnabled, securitySettings.isGuarantorsEnabled) &&
        Objects.equals(this.requiredGuaranties, securitySettings.requiredGuaranties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isCollateralEnabled, isGuarantorsEnabled, requiredGuaranties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecuritySettings {\n");
    sb.append("    isCollateralEnabled: ").append(toIndentedString(isCollateralEnabled)).append("\n");
    sb.append("    isGuarantorsEnabled: ").append(toIndentedString(isGuarantorsEnabled)).append("\n");
    sb.append("    requiredGuaranties: ").append(toIndentedString(requiredGuaranties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

