# Stream config
spring:
  security:
    oauth2:
      client:
        registration:
          dbs:
            authorization-grant-type: client_credentials
            client-id: bb-client
            client-secret: bb-secret
            client-authentication-method: post
        provider:
          dbs:
            token-uri: http://token-converter:8080/oauth/token
  activemq:
    broker-url: ${SPRING_ACTIVEMQ_BROKER_URL}
    password: ${SPRING_ACTIVEMQ_PASSWORD}
    user: ${SPRING_ACTIVEMQ_USER}
  jms:
    pub-sub-domain: true
  r2dbc:
    name: ${SPRING_R2DBC_NAME}
    password: ${SPRING_R2DBC_PASSWORD}
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}

logging:
  level:
    root: info
    sun: off
    javax: off
    org.apache.activemq: off
    jdk: off
backbase:
  stream:
    start:
      title: "Stream Mambu"
      subTitle: Stream <strong class="highlight">Mambu</strong>
      header: Stream <strong class="highlight">Mambu</strong>
      description: "Seamlessly integrate with Mambu with Stream Mambu. This service is provides an implementation for Account Integration Services, Transactions and Payments"
      footer: "MAMBU"
      defaultAction:
        name: Swagger
        href: swagger-ui.html
      navbarLinks:
        - name: Communtiy
          href: https://community.backbase.com

    dbs:
      user-manager-base-url: http://user-manager:8080
      access-control-base-url: http://access-control:8080
      arrangement-manager-base-url: http://arrangement-manager:8080
      transaction-manager-base-url: http://transaction-manager:8080
      limits-manager-base-url: http://limits-manager:8080
    mambu:
      base-url: ${BACKBASE_STREAM_MAMBU_BASE_URL}
      username: ${BACKBASE_STREAM_MAMBU_USERNAME}
      password: ${BACKBASE_STREAM_MAMBU_PASSWORD}
      mapping:
        product:
          deposit-account-type-mapping:
            CURRENT_ACCOUNT: "Current Account"
            REGULAR_SAVINGS: "Savings Account"
            FIXED_DEPOSIT: "Term Deposit"
            SAVINGS_PLAN: "Savings Account"
            INVESTOR_ACCOUNT: "Investment Account"
          loan-account-type-mapping:
            FIXED_TERM_LOAN: "Loan"
            DYNAMIC_TERM_LOAN: "Loan"
            INTEREST_FREE_LOAN: "Loan"
            TRANCHED_LOAN: "Loan"
            REVOLVING_CREDIT: "Loan"
        transactions:
          transaction-type-group-map:
            IMPORT: "Payment"
            WRITE_OFF: "Withdrawal"
            WRITE_OFF_ADJUSTMENT: "Fees"
            DEPOSIT: "Payment"
            ADJUSTMENT: "Fees"
            WITHDRAWAL: "Withdrawal"
            WITHDRAWAL_ADJUSTMENT: "Fees"
            CARD_TRANSACTION_REVERSAL: "Fees"
            TRANSFER: "Payment"
            TRANSFER_ADJUSTMENT: "Fees"
            FEE_APPLIED: "Fees"
            FEE_ADJUSTED: "Fees"
            FEES_DUE_REDUCED: "Fees"
            INTEREST_APPLIED: "Fees"
            INTEREST_APPLIED_ADJUSTMENT: "Fees"
            FEE_REDUCTION_ADJUSTMENT: "Fees"
            WITHHOLDING_TAX: "Fees"
            WITHHOLDING_TAX_ADJUSTMENT: "Fees"
            INTEREST_RATE_CHANGED: "Fees"
            OVERDRAFT_INTEREST_RATE_CHANGED: "Fees"
            OVERDRAFT_LIMIT_CHANGED: "Fees"
            BRANCH_CHANGED: "Fees"
            LOAN_FUNDED: "Loans"
            LOAN_FUNDED_ADJUSTMENT: "Loans"
            LOAN_REPAID: "Loans"
            LOAN_REPAID_ADJUSTMENT: "Loans"
            LOAN_FRACTION_BOUGHT: "Loans"
            LOAN_FRACTION_BOUGHT_ADJUSTMENT: "Loans"
            LOAN_FRACTION_SOLD: "Loans"
            LOAN_FRACTION_SOLD_ADJUSTMENT: "Loans"
          transaction-type-map:
            IMPORT: "Withdrawal"
            WRITE_OFF: "Withdrawal"
            WRITE_OFF_ADJUSTMENT: "Fee"
            DEPOSIT: "Deposit"
            ADJUSTMENT: "Fee"
            WITHDRAWAL: "Withdrawal"
            WITHDRAWAL_ADJUSTMENT: "Fee"
            CARD_TRANSACTION_REVERSAL: "Fee"
            TRANSFER: "Withdrawal"
            TRANSFER_ADJUSTMENT: "Fee"
            FEE_APPLIED: "Fee"
            FEE_ADJUSTED: "Fee"
            FEES_DUE_REDUCED: "Fee"
            INTEREST_APPLIED: "Fee"
            INTEREST_APPLIED_ADJUSTMENT: "Fee"
            FEE_REDUCTION_ADJUSTMENT: "Fee"
            WITHHOLDING_TAX: "Fee"
            WITHHOLDING_TAX_ADJUSTMENT: "Fee"
            INTEREST_RATE_CHANGED: "Fee"
            OVERDRAFT_INTEREST_RATE_CHANGED: "Fee"
            OVERDRAFT_LIMIT_CHANGED: "Fee"
            BRANCH_CHANGED: "Fee"
            LOAN_FUNDED: "Deposit"
            LOAN_FUNDED_ADJUSTMENT: "Fee"
            LOAN_REPAID: "Withdrawal"
            LOAN_REPAID_ADJUSTMENT: "Fee"
            LOAN_FRACTION_BOUGHT: "Fee"
            LOAN_FRACTION_BOUGHT_ADJUSTMENT: "Fee"
            LOAN_FRACTION_SOLD: "Fee"
            LOAN_FRACTION_SOLD_ADJUSTMENT: "Fee"
