/*
 * loans
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.loans.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The loan account balance details.
 */
@ApiModel(description = "The loan account balance details.")
@JsonPropertyOrder({
  Balances.JSON_PROPERTY_INTEREST_FROM_ARREARS_PAID,
  Balances.JSON_PROPERTY_PRINCIPAL_DUE,
  Balances.JSON_PROPERTY_INTEREST_BALANCE,
  Balances.JSON_PROPERTY_HOLD_BALANCE,
  Balances.JSON_PROPERTY_PRINCIPAL_PAID,
  Balances.JSON_PROPERTY_PENALTY_DUE,
  Balances.JSON_PROPERTY_FEES_BALANCE,
  Balances.JSON_PROPERTY_PENALTY_BALANCE,
  Balances.JSON_PROPERTY_REDRAW_BALANCE,
  Balances.JSON_PROPERTY_INTEREST_FROM_ARREARS_BALANCE,
  Balances.JSON_PROPERTY_PRINCIPAL_BALANCE,
  Balances.JSON_PROPERTY_INTEREST_DUE,
  Balances.JSON_PROPERTY_PENALTY_PAID,
  Balances.JSON_PROPERTY_FEES_PAID,
  Balances.JSON_PROPERTY_INTEREST_FROM_ARREARS_DUE,
  Balances.JSON_PROPERTY_FEES_DUE,
  Balances.JSON_PROPERTY_INTEREST_PAID
})

public class Balances {
  public static final String JSON_PROPERTY_INTEREST_FROM_ARREARS_PAID = "interestFromArrearsPaid";
  private BigDecimal interestFromArrearsPaid;

  public static final String JSON_PROPERTY_PRINCIPAL_DUE = "principalDue";
  private BigDecimal principalDue;

  public static final String JSON_PROPERTY_INTEREST_BALANCE = "interestBalance";
  private BigDecimal interestBalance;

  public static final String JSON_PROPERTY_HOLD_BALANCE = "holdBalance";
  private BigDecimal holdBalance;

  public static final String JSON_PROPERTY_PRINCIPAL_PAID = "principalPaid";
  private BigDecimal principalPaid;

  public static final String JSON_PROPERTY_PENALTY_DUE = "penaltyDue";
  private BigDecimal penaltyDue;

  public static final String JSON_PROPERTY_FEES_BALANCE = "feesBalance";
  private BigDecimal feesBalance;

  public static final String JSON_PROPERTY_PENALTY_BALANCE = "penaltyBalance";
  private BigDecimal penaltyBalance;

  public static final String JSON_PROPERTY_REDRAW_BALANCE = "redrawBalance";
  private BigDecimal redrawBalance;

  public static final String JSON_PROPERTY_INTEREST_FROM_ARREARS_BALANCE = "interestFromArrearsBalance";
  private BigDecimal interestFromArrearsBalance;

  public static final String JSON_PROPERTY_PRINCIPAL_BALANCE = "principalBalance";
  private BigDecimal principalBalance;

  public static final String JSON_PROPERTY_INTEREST_DUE = "interestDue";
  private BigDecimal interestDue;

  public static final String JSON_PROPERTY_PENALTY_PAID = "penaltyPaid";
  private BigDecimal penaltyPaid;

  public static final String JSON_PROPERTY_FEES_PAID = "feesPaid";
  private BigDecimal feesPaid;

  public static final String JSON_PROPERTY_INTEREST_FROM_ARREARS_DUE = "interestFromArrearsDue";
  private BigDecimal interestFromArrearsDue;

  public static final String JSON_PROPERTY_FEES_DUE = "feesDue";
  private BigDecimal feesDue;

  public static final String JSON_PROPERTY_INTEREST_PAID = "interestPaid";
  private BigDecimal interestPaid;


   /**
   * The interest from arrears paid, indicates total interest from arrears paid into the account.
   * @return interestFromArrearsPaid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The interest from arrears paid, indicates total interest from arrears paid into the account.")
  @JsonProperty(JSON_PROPERTY_INTEREST_FROM_ARREARS_PAID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getInterestFromArrearsPaid() {
    return interestFromArrearsPaid;
  }




   /**
   * The principal due, indicates how much principal it&#39;s due at this moment.
   * @return principalDue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The principal due, indicates how much principal it's due at this moment.")
  @JsonProperty(JSON_PROPERTY_PRINCIPAL_DUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPrincipalDue() {
    return principalDue;
  }




   /**
   * The interest balance. Represents the total interest owned by the client, from now on (total interest accrued for account - interest paid).
   * @return interestBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The interest balance. Represents the total interest owned by the client, from now on (total interest accrued for account - interest paid).")
  @JsonProperty(JSON_PROPERTY_INTEREST_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getInterestBalance() {
    return interestBalance;
  }




   /**
   * The sum of all the authorization hold amounts on this account.
   * @return holdBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The sum of all the authorization hold amounts on this account.")
  @JsonProperty(JSON_PROPERTY_HOLD_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getHoldBalance() {
    return holdBalance;
  }




   /**
   * The principal paid, holds the value of the total paid into the account.
   * @return principalPaid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The principal paid, holds the value of the total paid into the account.")
  @JsonProperty(JSON_PROPERTY_PRINCIPAL_PAID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPrincipalPaid() {
    return principalPaid;
  }




   /**
   * The penalty due. Represents the total penalty amount due for the account.
   * @return penaltyDue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The penalty due. Represents the total penalty amount due for the account.")
  @JsonProperty(JSON_PROPERTY_PENALTY_DUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPenaltyDue() {
    return penaltyDue;
  }




   /**
   * The fees balance. Represents the total fees expected to be paid on this account at a given moment.
   * @return feesBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The fees balance. Represents the total fees expected to be paid on this account at a given moment.")
  @JsonProperty(JSON_PROPERTY_FEES_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getFeesBalance() {
    return feesBalance;
  }




   /**
   * The penalty balance. Represents the total penalty expected to be paid on this account at a given moment.
   * @return penaltyBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The penalty balance. Represents the total penalty expected to be paid on this account at a given moment.")
  @JsonProperty(JSON_PROPERTY_PENALTY_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPenaltyBalance() {
    return penaltyBalance;
  }




  public Balances redrawBalance(BigDecimal redrawBalance) {
    
    this.redrawBalance = redrawBalance;
    return this;
  }

   /**
   * The total redraw amount owned by the client, from now on.
   * @return redrawBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total redraw amount owned by the client, from now on.")
  @JsonProperty(JSON_PROPERTY_REDRAW_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getRedrawBalance() {
    return redrawBalance;
  }


  public void setRedrawBalance(BigDecimal redrawBalance) {
    this.redrawBalance = redrawBalance;
  }


   /**
   * The interest from arrears balance. Indicates interest from arrears owned by the client, from now on. (total interest from arrears accrued for account - interest from arrears paid).
   * @return interestFromArrearsBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The interest from arrears balance. Indicates interest from arrears owned by the client, from now on. (total interest from arrears accrued for account - interest from arrears paid).")
  @JsonProperty(JSON_PROPERTY_INTEREST_FROM_ARREARS_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getInterestFromArrearsBalance() {
    return interestFromArrearsBalance;
  }




   /**
   * The total principal owned by the client, from now on (principal disbursed - principal paid).
   * @return principalBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total principal owned by the client, from now on (principal disbursed - principal paid).")
  @JsonProperty(JSON_PROPERTY_PRINCIPAL_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPrincipalBalance() {
    return principalBalance;
  }




   /**
   * The interest due. Indicates how much interest it&#39;s due for the account at this moment.
   * @return interestDue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The interest due. Indicates how much interest it's due for the account at this moment.")
  @JsonProperty(JSON_PROPERTY_INTEREST_DUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getInterestDue() {
    return interestDue;
  }




   /**
   * The Penalty paid. Represents the total penalty amount paid for the account.
   * @return penaltyPaid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The Penalty paid. Represents the total penalty amount paid for the account.")
  @JsonProperty(JSON_PROPERTY_PENALTY_PAID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPenaltyPaid() {
    return penaltyPaid;
  }




   /**
   * The fees paid. Represents the total fees paid for the account.
   * @return feesPaid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The fees paid. Represents the total fees paid for the account.")
  @JsonProperty(JSON_PROPERTY_FEES_PAID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getFeesPaid() {
    return feesPaid;
  }




   /**
   * The interest from arrears due. Indicates how much interest from arrears it&#39;s due for the account at this moment.
   * @return interestFromArrearsDue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The interest from arrears due. Indicates how much interest from arrears it's due for the account at this moment.")
  @JsonProperty(JSON_PROPERTY_INTEREST_FROM_ARREARS_DUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getInterestFromArrearsDue() {
    return interestFromArrearsDue;
  }




   /**
   * The fees due. Representing the total fees due for the account.
   * @return feesDue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The fees due. Representing the total fees due for the account.")
  @JsonProperty(JSON_PROPERTY_FEES_DUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getFeesDue() {
    return feesDue;
  }




   /**
   * The interest paid, indicates total interest paid into the account.
   * @return interestPaid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The interest paid, indicates total interest paid into the account.")
  @JsonProperty(JSON_PROPERTY_INTEREST_PAID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getInterestPaid() {
    return interestPaid;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Balances balances = (Balances) o;
    return Objects.equals(this.interestFromArrearsPaid, balances.interestFromArrearsPaid) &&
        Objects.equals(this.principalDue, balances.principalDue) &&
        Objects.equals(this.interestBalance, balances.interestBalance) &&
        Objects.equals(this.holdBalance, balances.holdBalance) &&
        Objects.equals(this.principalPaid, balances.principalPaid) &&
        Objects.equals(this.penaltyDue, balances.penaltyDue) &&
        Objects.equals(this.feesBalance, balances.feesBalance) &&
        Objects.equals(this.penaltyBalance, balances.penaltyBalance) &&
        Objects.equals(this.redrawBalance, balances.redrawBalance) &&
        Objects.equals(this.interestFromArrearsBalance, balances.interestFromArrearsBalance) &&
        Objects.equals(this.principalBalance, balances.principalBalance) &&
        Objects.equals(this.interestDue, balances.interestDue) &&
        Objects.equals(this.penaltyPaid, balances.penaltyPaid) &&
        Objects.equals(this.feesPaid, balances.feesPaid) &&
        Objects.equals(this.interestFromArrearsDue, balances.interestFromArrearsDue) &&
        Objects.equals(this.feesDue, balances.feesDue) &&
        Objects.equals(this.interestPaid, balances.interestPaid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interestFromArrearsPaid, principalDue, interestBalance, holdBalance, principalPaid, penaltyDue, feesBalance, penaltyBalance, redrawBalance, interestFromArrearsBalance, principalBalance, interestDue, penaltyPaid, feesPaid, interestFromArrearsDue, feesDue, interestPaid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Balances {\n");
    sb.append("    interestFromArrearsPaid: ").append(toIndentedString(interestFromArrearsPaid)).append("\n");
    sb.append("    principalDue: ").append(toIndentedString(principalDue)).append("\n");
    sb.append("    interestBalance: ").append(toIndentedString(interestBalance)).append("\n");
    sb.append("    holdBalance: ").append(toIndentedString(holdBalance)).append("\n");
    sb.append("    principalPaid: ").append(toIndentedString(principalPaid)).append("\n");
    sb.append("    penaltyDue: ").append(toIndentedString(penaltyDue)).append("\n");
    sb.append("    feesBalance: ").append(toIndentedString(feesBalance)).append("\n");
    sb.append("    penaltyBalance: ").append(toIndentedString(penaltyBalance)).append("\n");
    sb.append("    redrawBalance: ").append(toIndentedString(redrawBalance)).append("\n");
    sb.append("    interestFromArrearsBalance: ").append(toIndentedString(interestFromArrearsBalance)).append("\n");
    sb.append("    principalBalance: ").append(toIndentedString(principalBalance)).append("\n");
    sb.append("    interestDue: ").append(toIndentedString(interestDue)).append("\n");
    sb.append("    penaltyPaid: ").append(toIndentedString(penaltyPaid)).append("\n");
    sb.append("    feesPaid: ").append(toIndentedString(feesPaid)).append("\n");
    sb.append("    interestFromArrearsDue: ").append(toIndentedString(interestFromArrearsDue)).append("\n");
    sb.append("    feesDue: ").append(toIndentedString(feesDue)).append("\n");
    sb.append("    interestPaid: ").append(toIndentedString(interestPaid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

