/*
 * loans
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.loans.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The custom predefined fees, they may be used as the expected predefined fees that will be applied on the disbursement.
 */
@ApiModel(description = "The custom predefined fees, they may be used as the expected predefined fees that will be applied on the disbursement.")
@JsonPropertyOrder({
  CustomPredefinedFee.JSON_PROPERTY_PREDEFINED_FEE_ENCODED_KEY,
  CustomPredefinedFee.JSON_PROPERTY_ENCODED_KEY,
  CustomPredefinedFee.JSON_PROPERTY_AMOUNT
})

public class CustomPredefinedFee {
  public static final String JSON_PROPERTY_PREDEFINED_FEE_ENCODED_KEY = "predefinedFeeEncodedKey";
  private String predefinedFeeEncodedKey;

  public static final String JSON_PROPERTY_ENCODED_KEY = "encodedKey";
  private String encodedKey;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private BigDecimal amount;


  public CustomPredefinedFee predefinedFeeEncodedKey(String predefinedFeeEncodedKey) {
    
    this.predefinedFeeEncodedKey = predefinedFeeEncodedKey;
    return this;
  }

   /**
   * The encoded key of the predefined fee
   * @return predefinedFeeEncodedKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The encoded key of the predefined fee")
  @JsonProperty(JSON_PROPERTY_PREDEFINED_FEE_ENCODED_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPredefinedFeeEncodedKey() {
    return predefinedFeeEncodedKey;
  }


  public void setPredefinedFeeEncodedKey(String predefinedFeeEncodedKey) {
    this.predefinedFeeEncodedKey = predefinedFeeEncodedKey;
  }


   /**
   * The encoded key of the custom predefined fee, auto generated, unique.
   * @return encodedKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The encoded key of the custom predefined fee, auto generated, unique.")
  @JsonProperty(JSON_PROPERTY_ENCODED_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEncodedKey() {
    return encodedKey;
  }




  public CustomPredefinedFee amount(BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * The amount of the custom fee.
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The amount of the custom fee.")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getAmount() {
    return amount;
  }


  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomPredefinedFee customPredefinedFee = (CustomPredefinedFee) o;
    return Objects.equals(this.predefinedFeeEncodedKey, customPredefinedFee.predefinedFeeEncodedKey) &&
        Objects.equals(this.encodedKey, customPredefinedFee.encodedKey) &&
        Objects.equals(this.amount, customPredefinedFee.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(predefinedFeeEncodedKey, encodedKey, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomPredefinedFee {\n");
    sb.append("    predefinedFeeEncodedKey: ").append(toIndentedString(predefinedFeeEncodedKey)).append("\n");
    sb.append("    encodedKey: ").append(toIndentedString(encodedKey)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

