/*
 * deposits/transactions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.deposit.transactions.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Holds the deposit overdraft settings for a transaction
 */
@ApiModel(description = "Holds the deposit overdraft settings for a transaction")
@JsonPropertyOrder({
  DepositOverdraftSettings.JSON_PROPERTY_OVERDRAFT_LIMIT
})

public class DepositOverdraftSettings {
  public static final String JSON_PROPERTY_OVERDRAFT_LIMIT = "overdraftLimit";
  private BigDecimal overdraftLimit;


  public DepositOverdraftSettings overdraftLimit(BigDecimal overdraftLimit) {
    
    this.overdraftLimit = overdraftLimit;
    return this;
  }

   /**
   * The overdraft limit that was set or changed in this transaction
   * @return overdraftLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The overdraft limit that was set or changed in this transaction")
  @JsonProperty(JSON_PROPERTY_OVERDRAFT_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getOverdraftLimit() {
    return overdraftLimit;
  }


  public void setOverdraftLimit(BigDecimal overdraftLimit) {
    this.overdraftLimit = overdraftLimit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositOverdraftSettings depositOverdraftSettings = (DepositOverdraftSettings) o;
    return Objects.equals(this.overdraftLimit, depositOverdraftSettings.overdraftLimit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(overdraftLimit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositOverdraftSettings {\n");
    sb.append("    overdraftLimit: ").append(toIndentedString(overdraftLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

