/*
 * deposits/transactions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.deposit.transactions.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The balances changed within a transaction.
 */
@ApiModel(description = "The balances changed within a transaction.")
@JsonPropertyOrder({
  DepositTransactionBalances.JSON_PROPERTY_TOTAL_BALANCE
})

public class DepositTransactionBalances {
  public static final String JSON_PROPERTY_TOTAL_BALANCE = "totalBalance";
  private BigDecimal totalBalance;


  public DepositTransactionBalances totalBalance(BigDecimal totalBalance) {
    
    this.totalBalance = totalBalance;
    return this;
  }

   /**
   * The running balance owed by deposit
   * @return totalBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The running balance owed by deposit")
  @JsonProperty(JSON_PROPERTY_TOTAL_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTotalBalance() {
    return totalBalance;
  }


  public void setTotalBalance(BigDecimal totalBalance) {
    this.totalBalance = totalBalance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositTransactionBalances depositTransactionBalances = (DepositTransactionBalances) o;
    return Objects.equals(this.totalBalance, depositTransactionBalances.totalBalance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalBalance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositTransactionBalances {\n");
    sb.append("    totalBalance: ").append(toIndentedString(totalBalance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

