/*
 * deposits/transactions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.backbase.mambu.deposit.transactions.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Represents the transfer details, such as the linked transaction key
 */
@ApiModel(description = "Represents the transfer details, such as the linked transaction key")
@JsonPropertyOrder({
  TransferDetails.JSON_PROPERTY_LINKED_LOAN_TRANSACTION_KEY,
  TransferDetails.JSON_PROPERTY_LINKED_DEPOSIT_TRANSACTION_KEY
})

public class TransferDetails {
  public static final String JSON_PROPERTY_LINKED_LOAN_TRANSACTION_KEY = "linkedLoanTransactionKey";
  private String linkedLoanTransactionKey;

  public static final String JSON_PROPERTY_LINKED_DEPOSIT_TRANSACTION_KEY = "linkedDepositTransactionKey";
  private String linkedDepositTransactionKey;


  public TransferDetails linkedLoanTransactionKey(String linkedLoanTransactionKey) {
    
    this.linkedLoanTransactionKey = linkedLoanTransactionKey;
    return this;
  }

   /**
   * The key of the related loan transaction
   * @return linkedLoanTransactionKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The key of the related loan transaction")
  @JsonProperty(JSON_PROPERTY_LINKED_LOAN_TRANSACTION_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLinkedLoanTransactionKey() {
    return linkedLoanTransactionKey;
  }


  public void setLinkedLoanTransactionKey(String linkedLoanTransactionKey) {
    this.linkedLoanTransactionKey = linkedLoanTransactionKey;
  }


  public TransferDetails linkedDepositTransactionKey(String linkedDepositTransactionKey) {
    
    this.linkedDepositTransactionKey = linkedDepositTransactionKey;
    return this;
  }

   /**
   * The key of the related deposit transaction
   * @return linkedDepositTransactionKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The key of the related deposit transaction")
  @JsonProperty(JSON_PROPERTY_LINKED_DEPOSIT_TRANSACTION_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLinkedDepositTransactionKey() {
    return linkedDepositTransactionKey;
  }


  public void setLinkedDepositTransactionKey(String linkedDepositTransactionKey) {
    this.linkedDepositTransactionKey = linkedDepositTransactionKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferDetails transferDetails = (TransferDetails) o;
    return Objects.equals(this.linkedLoanTransactionKey, transferDetails.linkedLoanTransactionKey) &&
        Objects.equals(this.linkedDepositTransactionKey, transferDetails.linkedDepositTransactionKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkedLoanTransactionKey, linkedDepositTransactionKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferDetails {\n");
    sb.append("    linkedLoanTransactionKey: ").append(toIndentedString(linkedLoanTransactionKey)).append("\n");
    sb.append("    linkedDepositTransactionKey: ").append(toIndentedString(linkedDepositTransactionKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

